[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

; --- AGREGA ESTA LÍNEA ---
; Esto fuerza a que todas las librerías busquen archivos en la carpeta include/
build_flags = -Iinclude 

lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14